name: Deploy Backend to Replit

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/ -v
        
    - name: Deploy to Replit (instructions)
      run: |
        echo "To deploy to Replit:"
        echo "1. Import this repository to Replit"
        echo "2. Set up automatic GitHub sync in Replit"
        echo "3. Replit will automatically pull changes from this branch"