openapi: 3.0.1
info:
  title: Task Management API
  description: API for managing user tasks in the Hackathon II Todo Web App
  version: 1.0.0
servers:
  - url: http://localhost:8001
    description: Development server
  - url: https://api.hackathon-todo-app.com
    description: Production server
paths:
  /api/{user_id}/tasks:
    get:
      summary: Get all tasks for a user
      description: Retrieve all tasks associated with a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user whose tasks to retrieve
          schema:
            type: string
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: number
        '401':
          description: Unauthorized - invalid or expired JWT token
        '403':
          description: Forbidden - user trying to access another user's tasks
        '404':
          description: User not found
      security:
        - bearerAuth: []
    post:
      summary: Create a new task
      description: Create a new task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user to create the task for
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input data
        '401':
          description: Unauthorized - invalid or expired JWT token
        '403':
          description: Forbidden - user trying to create task for another user
      security:
        - bearerAuth: []
  /api/{user_id}/tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve details of a specific task by ID
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user who owns the task
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired JWT token
        '403':
          description: Forbidden - user trying to access another user's task
        '404':
          description: Task not found
      security:
        - bearerAuth: []
    put:
      summary: Update a task
      description: Update details of an existing task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user who owns the task
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input data
        '401':
          description: Unauthorized - invalid or expired JWT token
        '403':
          description: Forbidden - user trying to update another user's task
        '404':
          description: Task not found
      security:
        - bearerAuth: []
    delete:
      summary: Delete a task
      description: Delete a specific task by ID
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user who owns the task
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to delete
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - invalid or expired JWT token
        '403':
          description: Forbidden - user trying to delete another user's task
        '404':
          description: Task not found
      security:
        - bearerAuth: []
  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion status
      description: Update the completion status of a task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user who owns the task
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to update completion status
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: New completion status for the task
              required:
                - completed
      responses:
        '200':
          description: Task completion status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input data
        '401':
          description: Unauthorized - invalid or expired JWT token
        '403':
          description: Forbidden - user trying to update another user's task
        '404':
          description: Task not found
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 100
        description:
          type: string
          description: Detailed description of the task
          maxLength: 500
        completed:
          type: boolean
          description: Whether the task is completed or not
          default: false
        userId:
          type: string
          description: ID of the user who owns this task
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the task was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
        completedAt:
          type: string
          format: date-time
          description: Timestamp when the task was marked as completed (null if not completed)
      required:
        - id
        - title
        - completed
        - userId
        - createdAt
        - updatedAt
    TaskCreateRequest:
      type: object
      properties:
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 100
        description:
          type: string
          description: Detailed description of the task
          maxLength: 500
      required:
        - title
    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 100
        description:
          type: string
          description: Detailed description of the task
          maxLength: 500
        completed:
          type: boolean
          description: Whether the task is completed or not